-- ⚠️  DO NOT RUN THIS SCRIPT YET.
--
-- This is drafted for review only, as part of Sprint 1, per the approved
-- Phase 1 Foundation plan (Sprint 4: "Backfill legacy user, enforce NOT NULL
-- + FKs"). It is intentionally NOT executed in Sprint 1 and creates no rows
-- until:
--
--   1. Owner Decision #4 (approved plan, §11) is resolved: which email
--      should own the platform's existing single-tenant data as "user #1"?
--   2. Sprint 3 has added nullable user_id columns to the 12 non-settings
--      user-scoped tables (this script assumes those columns already exist).
--
-- Replace 'owner@dk-ai-os.local' below with the real, approved email before
-- this is ever run against any database, including a dev/staging one.

-- INSERT INTO users (email, display_name, role)
-- VALUES ('owner@dk-ai-os.local', 'Legacy Owner', 'user')
-- RETURNING id;
--
-- -- Then, for each of the 12 backfill-eligible tables (trades, journal_entries,
-- -- ai_messages, backtest_results, ai_lessons, trade_explanations,
-- -- greeks_quiz_results, daily_reports, stock_analysis_history,
-- -- value_watchlist, value_quiz_results, scanner_results):
-- --
-- -- UPDATE <table> SET user_id = '<the returned id above>' WHERE user_id IS NULL;
--
-- -- settings is handled separately in Sprint 5 (schema + code shipped together,
-- -- per the approved plan's §2.3) — not part of this generic backfill.

-- ─── Rollback ────────────────────────────────────────────────────────────
-- Once actually run: deleting the legacy user row requires first nulling out
-- every table's user_id FK referencing it, or the FK constraint will block
-- the delete (by design — see §2.4, ON DELETE RESTRICT). This is deliberate:
-- it is far safer for a legacy-data rollback to fail loudly than to silently
-- cascade-delete trade history.
