// AI Teacher & Learning Centre sprint — the Glossary. Deterministic,
// version-controlled term definitions (a plain TypeScript literal, not
// LLM-generated, not fetched from anywhere) covering every category the
// Learning Paths cover: Foundations, Options Greeks, Volatility, Options
// Strategies, Portfolio, Performance, and Institutional Thinking.
//
// Every term cross-links to related terms (by key) and related lessons
// (by learning-path topic key, see lib/learningPaths.ts) so the
// frontend can render "See also" / "Read the lesson" links in both
// directions without a second data source drifting out of sync.

export type GlossaryCategory =
  | "foundations"
  | "greeks"
  | "volatility"
  | "strategies"
  | "portfolio"
  | "performance"
  | "institutional"
  | "value-investing"
  | "trading"
  // v1.4.0, Sprint L1 — Learning Centre Foundation. Platform-mechanics
  // vocabulary (navigation, sessions, kill switches) — distinct from every
  // other category above, which teaches investing/trading/options
  // concepts, never how to operate the software itself.
  | "platform";

export interface GlossaryTerm {
  key: string;
  term: string;
  category: GlossaryCategory;
  definition: string;
  relatedTermKeys: string[];
  relatedLessonKeys: string[];
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  // ─── Foundations ────────────────────────────────────────────────────
  {
    key: "stock",
    term: "Stock",
    category: "foundations",
    definition: "A share of ownership in a company. Owning a stock entitles you to a proportional claim on the company's assets and earnings, and its price moves with the market's view of the company's prospects.",
    relatedTermKeys: ["option", "underlying"],
    relatedLessonKeys: ["foundations-stocks"],
  },
  {
    key: "option",
    term: "Option",
    category: "foundations",
    definition: "A contract giving the buyer the right, but not the obligation, to buy (a call) or sell (a put) 100 shares of an underlying stock at a fixed strike price on or before a fixed expiration date, in exchange for a premium paid to the seller.",
    relatedTermKeys: ["call", "put", "strike-price", "premium", "expiration"],
    relatedLessonKeys: ["foundations-options"],
  },
  {
    key: "call",
    term: "Call Option",
    category: "foundations",
    definition: "An option giving the buyer the right to BUY 100 shares at the strike price. Call buyers profit when the underlying rises above the strike plus the premium paid; call sellers collect the premium and profit if the underlying stays below the strike.",
    relatedTermKeys: ["option", "put", "assignment"],
    relatedLessonKeys: ["foundations-calls"],
  },
  {
    key: "put",
    term: "Put Option",
    category: "foundations",
    definition: "An option giving the buyer the right to SELL 100 shares at the strike price. Put buyers profit when the underlying falls below the strike minus the premium paid; put sellers collect the premium and profit if the underlying stays above the strike.",
    relatedTermKeys: ["option", "call", "assignment"],
    relatedLessonKeys: ["foundations-puts"],
  },
  {
    key: "strike-price",
    term: "Strike Price",
    category: "foundations",
    definition: "The fixed price at which an option's underlying shares can be bought (call) or sold (put). Where the strike sits relative to the current underlying price determines whether the option is in-, at-, or out-of-the-money.",
    relatedTermKeys: ["option", "in-the-money", "out-of-the-money", "at-the-money"],
    relatedLessonKeys: ["foundations-strike-price"],
  },
  {
    key: "premium",
    term: "Premium",
    category: "foundations",
    definition: "The price of an option, paid by the buyer to the seller. Premium is made up of intrinsic value (how far in-the-money the option already is) plus extrinsic/time value (which decays toward zero as expiration approaches).",
    relatedTermKeys: ["option", "theta", "premium-collected"],
    relatedLessonKeys: ["foundations-premium"],
  },
  {
    key: "expiration",
    term: "Expiration",
    category: "foundations",
    definition: "The date an option contract stops existing. After expiration, an in-the-money option is automatically exercised/assigned (for most US equity options) and an out-of-the-money option expires worthless.",
    relatedTermKeys: ["option", "assignment", "theta"],
    relatedLessonKeys: ["foundations-expiration"],
  },
  {
    key: "assignment",
    term: "Assignment",
    category: "foundations",
    definition: "What happens to the SELLER of an option when the buyer exercises it: the seller of a call must deliver 100 shares at the strike; the seller of a put must buy 100 shares at the strike. American-style equity options can be assigned at any time before expiration, not only at expiration. This platform never simulates or automates an actual assignment event — no shares are transferred, no position is auto-closed — it only computes a real, DTE- and moneyness-driven assignment RISK LEVEL to warn you before it happens.",
    relatedTermKeys: ["call", "put", "exercise"],
    relatedLessonKeys: ["foundations-assignment", "options-risk-management"],
  },
  {
    key: "exercise",
    term: "Exercise",
    category: "foundations",
    definition: "What the BUYER of an option does to invoke their right to buy (call) or sell (put) the underlying at the strike price. Exercising a call is choosing to buy; exercising a put is choosing to sell.",
    relatedTermKeys: ["assignment", "call", "put"],
    relatedLessonKeys: ["foundations-assignment"],
  },
  {
    key: "in-the-money",
    term: "In-the-Money (ITM)",
    category: "foundations",
    definition: "An option with positive intrinsic value: a call whose strike is below the current underlying price, or a put whose strike is above it. ITM options carry higher assignment risk.",
    relatedTermKeys: ["strike-price", "out-of-the-money", "at-the-money", "assignment"],
    relatedLessonKeys: ["foundations-strike-price"],
  },
  {
    key: "out-of-the-money",
    term: "Out-of-the-Money (OTM)",
    category: "foundations",
    definition: "An option with zero intrinsic value: a call whose strike is above the current underlying price, or a put whose strike is below it. OTM options are pure time value and expire worthless if the underlying never crosses the strike.",
    relatedTermKeys: ["strike-price", "in-the-money", "at-the-money"],
    relatedLessonKeys: ["foundations-strike-price"],
  },
  {
    key: "at-the-money",
    term: "At-the-Money (ATM)",
    category: "foundations",
    definition: "An option whose strike price sits at (or very near) the current underlying price. ATM options carry the most extrinsic value, the fastest theta decay, and the highest gamma and vega.",
    relatedTermKeys: ["strike-price", "in-the-money", "out-of-the-money", "gamma"],
    relatedLessonKeys: ["foundations-strike-price"],
  },
  {
    key: "option-intrinsic-value",
    term: "Intrinsic Value (Options)",
    category: "foundations",
    definition: "The portion of an option's premium that reflects real, already-realized in-the-money value: max(0, underlying price − strike) for a call, max(0, strike − underlying price) for a put. An out-of-the-money option always has zero intrinsic value. This platform's own risk engine computes real intrinsic value at the exact price points it uses to size worst-case loss — a genuine, load-bearing calculation, not just teaching prose. (Distinct from the unrelated \"Intrinsic Value\" glossary entry in the Value Investing category, which describes a company's own estimated fair worth, not an option's.)",
    relatedTermKeys: ["extrinsic-value", "premium", "in-the-money"],
    relatedLessonKeys: ["foundations-options"],
  },
  {
    key: "extrinsic-value",
    term: "Extrinsic Value (Time Value)",
    category: "foundations",
    definition: "The portion of an option's premium beyond its intrinsic value — compensation for the time remaining and the uncertainty of where the underlying might move before expiration. Extrinsic value decays toward zero as expiration approaches (see Theta); an at-the-money or out-of-the-money option's entire premium is extrinsic value. This platform never computes or returns a standalone extrinsic-value number — only the total premium and, separately, intrinsic value.",
    relatedTermKeys: ["option-intrinsic-value", "premium", "theta"],
    relatedLessonKeys: ["foundations-options"],
  },
  {
    key: "contract-multiplier",
    term: "Contract Multiplier",
    category: "foundations",
    definition: "The number of underlying shares one option contract controls — 100, for every equity option on this platform. Every dollar figure this platform computes (credit, max profit, max loss, theta, vega, notional) multiplies the per-share number by 100 consistently, not just in teaching examples.",
    relatedTermKeys: ["option", "premium"],
    relatedLessonKeys: ["foundations-options"],
  },
  {
    key: "option-chain",
    term: "Options Chain",
    category: "foundations",
    definition: "A table listing every available strike (and, on some platforms, every expiration) for an underlying's options, typically with calls on one side and puts on the other. This platform's own Option Chain page shows calls and puts around the current price for one fixed expiration, with delta/theta/IV/bid/mid/ask per strike — it does not currently let you switch between expirations.",
    relatedTermKeys: ["strike-price", "bid-ask-spread", "open-interest"],
    relatedLessonKeys: ["options-chain-contract-selection"],
  },
  {
    key: "bid-ask-spread",
    term: "Bid/Ask Spread",
    category: "foundations",
    definition: "The gap between the highest price a buyer is currently willing to pay (bid) and the lowest price a seller will accept (ask) for a contract. A wide spread (relative to the contract's own mid price) is a direct sign of poor liquidity — you'd give up real money crossing it to enter or exit immediately. This platform enforces a maximum spread percentage before a contract can even reach a scanner result or trade ticket, rejecting anything wider.",
    relatedTermKeys: ["open-interest", "option-chain"],
    relatedLessonKeys: ["options-chain-contract-selection"],
  },
  {
    key: "open-interest",
    term: "Open Interest (OI)",
    category: "foundations",
    definition: "The total number of contracts of a given strike/expiration currently open (not yet closed or expired) across all market participants. Low open interest is a real liquidity warning — few other traders are in that exact contract, so exiting later may be difficult or costly. This platform enforces a minimum open-interest threshold before a contract is allowed into a scan result, though the figure itself isn't shown as its own column on the Option Chain page.",
    relatedTermKeys: ["bid-ask-spread", "option-chain"],
    relatedLessonKeys: ["options-chain-contract-selection"],
  },
  {
    key: "breakeven",
    term: "Breakeven Price",
    category: "foundations",
    definition: "The underlying price at which a position neither makes nor loses money at expiration. A credit spread typically has one breakeven per side (short strike ± net credit received); a single option has one. This platform computes real breakevens for the strategies it structurally supports (iron condors, iron flies) and honestly reports them unavailable, with a stated reason, for strategies its math doesn't yet cover — never a fabricated number.",
    relatedTermKeys: ["max-profit", "max-loss", "premium"],
    relatedLessonKeys: ["volatility-pricing-probability"],
  },
  {
    key: "defined-risk",
    term: "Defined Risk vs. Undefined Risk",
    category: "foundations",
    definition: "A defined-risk position has a maximum possible loss that's known and fixed at entry (e.g. a credit spread's width minus credit received). An undefined-risk (\"naked\") position — a short call or put with no offsetting long option — has a loss that is theoretically unlimited (a naked call) or very large (a naked put, capped only by the stock going to zero). This platform's own execution engine structurally blocks every naked position before it can ever be opened — undefined risk is a real, important concept to understand, but not one this platform's own trade flow will ever let you enter.",
    relatedTermKeys: ["max-loss", "buying-power"],
    relatedLessonKeys: ["options-risk-management"],
  },

  // ─── Greeks ──────────────────────────────────────────────────────────
  {
    key: "delta",
    term: "Delta",
    category: "greeks",
    definition: "How much an option's price moves per $1 move in the underlying. Calls run 0 to +1, puts 0 to −1. Delta also approximates the probability an option finishes in the money, and the signed sum of every leg's delta gives a position's overall directional exposure.",
    relatedTermKeys: ["gamma", "portfolio-greeks", "probability-of-profit"],
    relatedLessonKeys: ["greeks-delta"],
  },
  {
    key: "gamma",
    term: "Gamma",
    category: "greeks",
    definition: "The rate of change of delta as the underlying moves. High gamma means delta swings rapidly — largest for at-the-money options close to expiration. Premium sellers are typically short gamma, so risk accelerates on a fast move.",
    relatedTermKeys: ["delta", "at-the-money"],
    relatedLessonKeys: ["greeks-gamma"],
  },
  {
    key: "theta",
    term: "Theta",
    category: "greeks",
    definition: "The dollar amount an option's price decays per calendar day, all else equal. Decay accelerates near expiration and is fastest for at-the-money options. For a buyer theta is a cost; for a seller it is income.",
    relatedTermKeys: ["premium", "theta-income", "expiration"],
    relatedLessonKeys: ["greeks-theta"],
  },
  {
    key: "vega",
    term: "Vega",
    category: "greeks",
    definition: "How much an option's price moves per 1-percentage-point change in implied volatility. Vega is largest for at-the-money, longer-dated options. Premium sellers are usually short vega and benefit from falling IV.",
    relatedTermKeys: ["implied-volatility", "iv-crush"],
    relatedLessonKeys: ["greeks-vega"],
  },
  {
    key: "rho",
    term: "Rho",
    category: "greeks",
    definition: "How much an option's price moves per 1-percentage-point change in interest rates. Rho is usually the smallest, least-watched Greek for short-dated equity options, since rate moves are slow relative to an option's life.",
    relatedTermKeys: ["delta", "theta"],
    relatedLessonKeys: ["greeks-rho"],
  },
  {
    key: "portfolio-greeks",
    term: "Portfolio Greeks",
    category: "greeks",
    definition: "The sum of every open position's own Greeks, giving one net figure for the whole account (e.g. net delta, net theta). This is the number that actually describes your total directional/time/volatility exposure — not any single position's own Greeks in isolation.",
    relatedTermKeys: ["delta", "theta", "gamma", "vega"],
    relatedLessonKeys: ["greeks-portfolio-greeks"],
  },

  // ─── Volatility ──────────────────────────────────────────────────────
  {
    key: "implied-volatility",
    term: "Implied Volatility (IV)",
    category: "volatility",
    definition: "The market's forward-looking estimate of how much a stock will move, backed out of an option's own price. Higher IV means richer option premiums on both calls and puts. IV tends to rise before uncertain events (like earnings) and fall afterward.",
    relatedTermKeys: ["historical-volatility", "iv-rank", "vega", "iv-crush"],
    relatedLessonKeys: ["volatility-iv"],
  },
  {
    key: "historical-volatility",
    term: "Historical Volatility (HV)",
    category: "volatility",
    definition: "How much a stock has actually moved in the past, computed from its own historical price series (also called realized volatility) — the real-world counterpart to IV's forward-looking, market-implied estimate. This platform does not compute or display HV anywhere; no historical/realized-volatility calculation exists in the codebase. Comparing IV to HV is a genuine, standard professional technique — a trader would need a separate tool to do it against this platform's own data.",
    relatedTermKeys: ["implied-volatility", "expected-move"],
    relatedLessonKeys: ["volatility-hv"],
  },
  {
    key: "iv-rank",
    term: "IV Rank",
    category: "volatility",
    definition: "Where a stock's current implied volatility sits relative to its own 52-week IV range, expressed 0-100. A high IV rank means options are relatively expensive for THIS stock right now — the classic signal premium sellers look for before selling.",
    relatedTermKeys: ["implied-volatility", "iv-crush"],
    relatedLessonKeys: ["volatility-iv-rank"],
  },
  {
    key: "expected-move",
    term: "Expected Move",
    category: "volatility",
    definition: "The market-implied range a stock is likely to trade within by a given date, derived from implied volatility and time (IV × √(days/365)). It is a one-standard-deviation estimate, not a prediction — roughly a 68% chance the stock stays inside that range.",
    relatedTermKeys: ["implied-volatility", "historical-volatility"],
    relatedLessonKeys: ["volatility-expected-move"],
  },
  {
    key: "iv-crush",
    term: "IV Crush",
    category: "volatility",
    definition: "The sharp drop in implied volatility that typically follows a known event (most commonly earnings), once the uncertainty the market was pricing in has been resolved. Premium sellers structure earnings plays specifically to harvest this collapse.",
    relatedTermKeys: ["implied-volatility", "iv-rank", "earnings-volatility"],
    relatedLessonKeys: ["volatility-earnings"],
  },
  {
    key: "earnings-volatility",
    term: "Earnings Volatility",
    category: "volatility",
    definition: "The elevated implied volatility priced into an option ahead of a company's earnings report, reflecting genuine uncertainty about the result. It typically collapses (see IV Crush) the trading day after the report.",
    relatedTermKeys: ["iv-crush", "expected-move", "iv-rank"],
    relatedLessonKeys: ["volatility-earnings"],
  },

  // ─── Strategies ──────────────────────────────────────────────────────
  // v1.4.0, Sprint L2G — Options Strategies Academy. New terms:
  // long-call, long-put, protective-put, bull-call-spread, bear-put-spread,
  // bull-put-spread, bear-call-spread, wing-width. covered-call's and
  // vertical-spread's own definitions gained a short honesty disclosure,
  // matching Sprint L2F's precedent for historical-volatility/event-risk.
  {
    key: "long-call",
    term: "Long Call",
    category: "strategies",
    definition: "Buying a call option outright: a bullish, defined-risk position where the maximum loss is the premium paid and the maximum profit is theoretically unlimited, since a stock's price has no upper cap. This platform's own scanner and execution engine do not build, price, or route an order for a standalone long call — only Iron Condor, Iron Fly, Calendar Spread, and Earnings are supported.",
    relatedTermKeys: ["call", "long-put", "delta", "theta", "breakeven"],
    relatedLessonKeys: ["strategies-long-call"],
  },
  {
    key: "long-put",
    term: "Long Put",
    category: "strategies",
    definition: "Buying a put option outright: a bearish, defined-risk position where the maximum loss is the premium paid and the maximum profit is large but capped (strike price minus premium, since a stock can only fall to zero). Like the long call, this is not a strategy this platform's own scanner or execution engine builds or trades.",
    relatedTermKeys: ["put", "long-call", "delta", "theta", "protective-put"],
    relatedLessonKeys: ["strategies-long-put"],
  },
  {
    key: "protective-put",
    term: "Protective Put",
    category: "strategies",
    definition: "Owning stock and buying a put against it as insurance: the put gains value if the stock falls, putting a floor under the combined position's downside in exchange for the ongoing cost of the premium. This concept has zero implementation anywhere on this platform — no scanner support, no execution builder, no reference page — it is purely conceptual, hedging-theory education.",
    relatedTermKeys: ["long-put", "put", "defined-risk"],
    relatedLessonKeys: ["strategies-protective-put"],
  },
  {
    key: "bull-call-spread",
    term: "Bull Call Spread",
    category: "strategies",
    definition: "A debit vertical spread: buy a lower-strike call, sell a higher-strike call, same expiration. A bullish, capped-upside, capped-cost alternative to an outright long call. Not independently order-routable on this platform.",
    relatedTermKeys: ["vertical-spread", "bear-put-spread", "long-call"],
    relatedLessonKeys: ["strategies-verticals"],
  },
  {
    key: "bear-put-spread",
    term: "Bear Put Spread",
    category: "strategies",
    definition: "A debit vertical spread: buy a higher-strike put, sell a lower-strike put, same expiration. A bearish, capped-upside, capped-cost alternative to an outright long put — the mirror image of a bull call spread. Not independently order-routable on this platform.",
    relatedTermKeys: ["vertical-spread", "bull-call-spread", "long-put"],
    relatedLessonKeys: ["strategies-verticals"],
  },
  {
    key: "bull-put-spread",
    term: "Bull Put Spread",
    category: "strategies",
    definition: "A credit vertical spread: sell a higher-strike put, buy a lower-strike put, same expiration. Profits if the stock stays above the short strike; the credit collected is the maximum profit. Not independently order-routable on this platform — but this exact structure is literally the put-side half of every real Iron Condor this platform's scanner and execution engine build.",
    relatedTermKeys: ["vertical-spread", "bear-call-spread", "iron-condor"],
    relatedLessonKeys: ["strategies-verticals", "strategies-iron-condor"],
  },
  {
    key: "bear-call-spread",
    term: "Bear Call Spread",
    category: "strategies",
    definition: "A credit vertical spread: sell a lower-strike call, buy a higher-strike call, same expiration. Profits if the stock stays below the short strike; the credit collected is the maximum profit. Not independently order-routable on this platform — but this exact structure is literally the call-side half of every real Iron Condor this platform's scanner and execution engine build.",
    relatedTermKeys: ["vertical-spread", "bull-put-spread", "iron-condor"],
    relatedLessonKeys: ["strategies-verticals", "strategies-iron-condor"],
  },
  {
    key: "wing-width",
    term: "Wing Width",
    category: "strategies",
    definition: "The distance between a credit spread's short strike and its protective long strike — this defines the position's maximum loss. On this platform, wing width is computed automatically (roughly 2.5% of the underlying's price for an Iron Condor, roughly 5% for an Iron Fly) rather than being a manually adjustable input.",
    relatedTermKeys: ["iron-condor", "iron-butterfly", "vertical-spread"],
    relatedLessonKeys: ["strategies-iron-condor", "strategies-iron-butterfly"],
  },
  {
    key: "covered-call",
    term: "Covered Call",
    category: "strategies",
    definition: "Owning 100 shares of stock and selling a call option against them. Collects premium income and caps upside at the strike; the stock itself remains the primary risk (a falling stock still loses value, only partly offset by the premium collected). This platform's own execution and scanning engine do not build or price this strategy — a Strategy Academy reference page and a Payoff Diagram Simulator are available for education only.",
    relatedTermKeys: ["call", "cash-secured-put", "wheel"],
    relatedLessonKeys: ["strategies-covered-calls"],
  },
  {
    key: "cash-secured-put",
    term: "Cash Secured Put (CSP)",
    category: "strategies",
    definition: "Selling a put option while holding enough cash to buy 100 shares at the strike if assigned. Collects premium income; if the stock falls below the strike, you're assigned and own the shares at an effective cost basis reduced by the premium collected.",
    relatedTermKeys: ["put", "covered-call", "wheel", "assignment"],
    relatedLessonKeys: ["strategies-csp"],
  },
  {
    key: "wheel",
    term: "The Wheel",
    category: "strategies",
    definition: "A cyclical income strategy: sell cash-secured puts on a stock you're willing to own; if assigned, sell covered calls on the resulting shares until they're called away; then return to selling puts. Designed to collect premium at every stage of the cycle.",
    relatedTermKeys: ["cash-secured-put", "covered-call"],
    relatedLessonKeys: ["strategies-wheel"],
  },
  {
    key: "vertical-spread",
    term: "Vertical Spread",
    category: "strategies",
    definition: "Buying and selling two options of the same type (both calls or both puts) and expiration, at different strikes. Defines both maximum profit and maximum loss up front. Four named variants exist — Bull Call Spread, Bear Put Spread, Bull Put Spread, Bear Call Spread — none independently order-routable on this platform, but the two credit variants (Bull Put, Bear Call) are literally the building blocks of an Iron Condor's own put and call spreads.",
    relatedTermKeys: ["iron-condor", "strike-price", "bull-call-spread", "bear-put-spread", "bull-put-spread", "bear-call-spread"],
    relatedLessonKeys: ["strategies-verticals"],
  },
  {
    key: "iron-condor",
    term: "Iron Condor",
    category: "strategies",
    definition: "A defined-risk, credit-collecting strategy combining a short put spread below the market and a short call spread above it. Profits when the underlying stays between the two short strikes through expiration; this platform's own scanner and execution engine build and price real iron condors.",
    relatedTermKeys: ["vertical-spread", "iron-butterfly", "delta"],
    relatedLessonKeys: ["strategies-iron-condor"],
  },
  {
    key: "iron-butterfly",
    term: "Iron Butterfly",
    category: "strategies",
    definition: "Like an iron condor, but both short strikes sit at the same at-the-money price. Collects the richest credit of the family but has the narrowest profit zone — maximum income, minimum margin for error.",
    relatedTermKeys: ["iron-condor", "at-the-money", "vertical-spread"],
    relatedLessonKeys: ["strategies-iron-butterfly"],
  },
  {
    key: "calendar-spread",
    term: "Calendar Spread",
    category: "strategies",
    definition: "Selling a near-dated option and buying a longer-dated option at the same strike. Profits from the front-month option decaying faster than the back-month option, and from rising implied volatility on the longer-dated leg; this platform's own engine builds and prices real calendar spreads.",
    relatedTermKeys: ["diagonal-spread", "theta"],
    relatedLessonKeys: ["strategies-calendar"],
  },
  {
    key: "diagonal-spread",
    term: "Diagonal Spread",
    category: "strategies",
    definition: "Like a calendar spread, but the near- and far-dated legs use different strikes rather than the same one — combining a calendar's time-decay edge with a directional lean from the strike offset.",
    relatedTermKeys: ["calendar-spread", "vertical-spread"],
    relatedLessonKeys: ["strategies-diagonal"],
  },

  // ─── Portfolio ───────────────────────────────────────────────────────
  // v1.4.0, Sprint L2H — Institutional Options Portfolio Management
  // Academy. New terms: account-value, cash-balance, unrealized-pnl,
  // realized-pnl, max-portfolio-risk.
  {
    key: "account-value",
    term: "Account Value (Portfolio Value)",
    category: "portfolio",
    definition: "This platform's real-time estimate of what the account is worth right now — the account's baseline plus every open position's current unrealized P/L. Shown on the Account Snapshot panel of the Portfolio AI cockpit, not on the Portfolio Greeks page.",
    relatedTermKeys: ["unrealized-pnl", "buying-power"],
    relatedLessonKeys: ["portfolio-overview"],
  },
  {
    key: "cash-balance",
    term: "Cash Balance",
    category: "portfolio",
    definition: "Account value minus the risk dollars already committed to open trades — a real, computed backend figure, honestly disclosed as not currently rendered as its own labeled panel on any screen, even though the same endpoint that powers the Account Snapshot already returns it.",
    relatedTermKeys: ["account-value", "buying-power"],
    relatedLessonKeys: ["portfolio-overview"],
  },
  {
    key: "unrealized-pnl",
    term: "Unrealized P/L",
    category: "portfolio",
    definition: "The live, still-open mark-to-market gain or loss on a position that hasn't been closed yet. Shown per position on the Portfolio Greeks page, and rolled into this platform's own 'Day P/L' figure on the Account Snapshot — never a locked-in result until the position is actually closed.",
    relatedTermKeys: ["realized-pnl", "account-value"],
    relatedLessonKeys: ["portfolio-overview"],
  },
  {
    key: "realized-pnl",
    term: "Realized P/L",
    category: "portfolio",
    definition: "Profit or loss that's actually locked in because a trade has closed. This platform has no dedicated 'Realized P/L' field on its portfolio pages — the real, portfolio-wide realized-performance figure is the Total P&L KPI on the Performance Analytics page, computed only from trades that have actually closed.",
    relatedTermKeys: ["unrealized-pnl", "win-rate"],
    relatedLessonKeys: ["portfolio-overview"],
  },
  {
    key: "max-portfolio-risk",
    term: "Maximum Portfolio Risk",
    category: "portfolio",
    definition: "A hard, whole-account risk cap (a percentage of account value across every open trade combined) enforced by this platform's execution engine before any order — manual, semi-auto, or full-auto — can be submitted. A trade that would push the account over this line is rejected outright, distinct from the Position Sizing Calculator's own purely advisory sizing suggestion, which cannot block a trade.",
    relatedTermKeys: ["position-sizing", "buying-power"],
    relatedLessonKeys: ["portfolio-position-sizing"],
  },
  {
    key: "position-sizing",
    term: "Position Sizing",
    category: "portfolio",
    definition: "Deciding how much capital to risk on a single trade, typically bounded as a percentage of total account value. Disciplined position sizing is what prevents any one trade — however well-analyzed — from doing outsized damage to the portfolio.",
    relatedTermKeys: ["concentration", "buying-power"],
    relatedLessonKeys: ["portfolio-position-sizing"],
  },
  {
    key: "portfolio-health",
    term: "Portfolio Health",
    category: "portfolio",
    definition: "A single, blended 0-100 score this platform computes from Concentration, Diversification, Event Risk, Net Greeks Exposure, Directional Exposure, Position Sizing Quality, Position Count, and Expiration Distribution — a deterministic aggregation of already-computed risk factors, never a new statistical model.",
    relatedTermKeys: ["concentration", "diversification", "event-risk"],
    relatedLessonKeys: ["portfolio-health"],
  },
  {
    key: "buying-power",
    term: "Buying Power",
    category: "portfolio",
    definition: "The capital available in an account to open new positions, after accounting for the margin/risk already committed to open trades. Selling defined-risk spreads (like an iron condor) ties up buying power equal to the maximum loss.",
    relatedTermKeys: ["position-sizing", "max-loss"],
    relatedLessonKeys: ["portfolio-buying-power", "options-risk-management"],
  },
  {
    key: "concentration",
    term: "Concentration",
    category: "portfolio",
    definition: "How much of a portfolio's risk sits in a single symbol, sector, strategy, or expiration date. High concentration means one adverse move can affect a large share of the account at once — the opposite of diversification.",
    relatedTermKeys: ["diversification", "correlation", "position-sizing"],
    relatedLessonKeys: ["portfolio-concentration", "options-risk-management"],
  },
  {
    key: "diversification",
    term: "Diversification",
    category: "portfolio",
    definition: "Spreading risk across multiple symbols, sectors, strategies, and expirations so no single adverse event can materially damage the whole portfolio. The inverse measure of concentration.",
    relatedTermKeys: ["concentration", "correlation"],
    relatedLessonKeys: ["portfolio-diversification"],
  },
  {
    key: "portfolio-optimisation",
    term: "Portfolio Optimisation (Upgrade / Trim / Exit Candidates)",
    category: "portfolio",
    definition:
      "A deterministic review of an existing portfolio's own holdings, classifying each into Exit (the Decision Engine already recommends Sell/Avoid), Trim (a Reduce recommendation, or a position/sector above its concentration cap), Upgrade (a mediocre Hold with a real, meaningfully-better same-sector alternative available), or Core (no change suggested) — reusing the Decision Engine's own recommendation and Opportunity Discovery's own ranked universe, never a new score.",
    relatedTermKeys: ["concentration", "diversification", "position-sizing", "capital-allocation"],
    relatedLessonKeys: [],
  },
  {
    key: "investment-committee-workbench",
    term: "Investment Committee Workbench",
    category: "portfolio",
    definition:
      "A single, sequential review workflow — select a company, review its research/valuation/Decision Engine/Portfolio Optimisation/Monitoring outputs, generate a deterministic Investment Memo, and record a Committee decision — all reused from already-computed engines. The Investment Memo assembles 14 sections (Business Summary through Conclusion) entirely from existing outputs; a recorded Committee decision is the same Decision Engine snapshot already used for Decision Timeline / Meeting History elsewhere in the platform. Never a new valuation model, never a new score.",
    relatedTermKeys: ["portfolio-optimisation"],
    relatedLessonKeys: [],
  },
  {
    key: "research-terminal",
    term: "Institutional Research Terminal",
    category: "portfolio",
    definition:
      "A professional, multi-panel research workspace unifying every existing Engine 1 capability into one screen: Company Search, an Analyse mode (Overview, Financial Statements, Decision Engine, Investment Committee, Investment Memo, Portfolio Impact, Monitoring, Evidence, and Research Notes tabs), a Compare mode (side-by-side valuation across any number of symbols, reusing Opportunity Discovery's own comparison engine), and a Split-screen mode (two full research panels side by side). Named layouts (which symbols are open, which mode, which tab) can be saved for later. Every figure shown is a direct reuse of an already-computed engine — no new valuation model, no new score.",
    relatedTermKeys: ["investment-committee-workbench", "portfolio-optimisation"],
    relatedLessonKeys: [],
  },
  {
    key: "correlation",
    term: "Correlation",
    category: "portfolio",
    definition: "How closely two positions' values tend to move together. Highly correlated positions (e.g. several tech-sector iron condors) don't provide real diversification even if the symbols differ, since they tend to gain or lose together.",
    relatedTermKeys: ["diversification", "concentration"],
    relatedLessonKeys: ["portfolio-correlation"],
  },
  {
    key: "stress-testing",
    term: "Stress Testing",
    category: "portfolio",
    definition: "Repricing every open position under a hypothetical shock (a price move, an IV spike, or time passing) to see how the portfolio's value and risk score would change — a what-if simulation over real, already-computed positions, not a forecast.",
    relatedTermKeys: ["event-risk", "portfolio-health"],
    relatedLessonKeys: ["portfolio-stress-testing"],
  },
  {
    key: "event-risk",
    term: "Event Risk",
    category: "portfolio",
    definition: "The risk that a scheduled event (earnings, an economic release, a dividend date) causes an outsized, sudden move in a position before you can react. This platform classifies each open position's own event-risk level from known upcoming event dates, explicitly self-labeled SIMULATED in its own data — a calendar/timing overlay, not a live news feed.",
    relatedTermKeys: ["earnings-volatility", "stress-testing"],
    relatedLessonKeys: ["portfolio-event-risk", "options-risk-management"],
  },

  // ─── Performance ─────────────────────────────────────────────────────
  {
    key: "win-rate",
    term: "Win Rate",
    category: "performance",
    definition: "The percentage of closed trades that were profitable. A useful but incomplete metric on its own — a high win rate with rare, large losses can still be a losing strategy overall (see Expectancy).",
    relatedTermKeys: ["expectancy", "probability-of-profit"],
    relatedLessonKeys: ["performance-win-rate"],
  },
  {
    key: "drawdown",
    term: "Drawdown",
    category: "performance",
    definition: "The decline from a portfolio's highest recorded value to a subsequent low, before a new high is made. Maximum drawdown is a key measure of how much pain a strategy can inflict along the way to its long-run return.",
    relatedTermKeys: ["win-rate", "expectancy"],
    relatedLessonKeys: ["performance-drawdown"],
  },
  {
    key: "theta-income",
    term: "Theta Income",
    category: "performance",
    definition: "The projected dollar income from time decay across every open position, summed into a daily/weekly/monthly figure — the practical, forward-looking counterpart to Premium Collected's own backward-looking, realized total.",
    relatedTermKeys: ["theta", "premium-collected"],
    relatedLessonKeys: ["performance-theta-income"],
  },
  {
    key: "premium-collected",
    term: "Premium Collected",
    category: "performance",
    definition: "The total credit actually received from selling options across closed (or currently open) trades — a realized, backward-looking figure, distinct from Theta Income's own forward-looking daily/weekly/monthly projection.",
    relatedTermKeys: ["premium", "theta-income"],
    relatedLessonKeys: ["performance-premium-collected"],
  },
  {
    key: "return-on-capital",
    term: "Return on Capital",
    category: "performance",
    definition: "Profit expressed as a percentage of the capital actually put at risk (typically max loss for a defined-risk spread), rather than as a raw dollar figure — the number that lets you compare trades of very different sizes on equal footing.",
    relatedTermKeys: ["max-loss", "expectancy"],
    relatedLessonKeys: ["performance-return-on-capital", "volatility-pricing-probability"],
  },
  {
    key: "expectancy",
    term: "Expectancy",
    category: "performance",
    definition: "The average dollar result you'd expect per trade over a large sample, combining win rate with average win and average loss size: (win rate × avg win) − (loss rate × avg loss). Positive expectancy is what makes a strategy sustainable over time, regardless of any single trade's outcome.",
    relatedTermKeys: ["win-rate", "expected-value"],
    relatedLessonKeys: ["performance-expectancy"],
  },

  // ─── Institutional Thinking ──────────────────────────────────────────
  {
    key: "portfolio-construction",
    term: "Portfolio Construction",
    category: "institutional",
    definition: "The deliberate process of deciding which positions to hold and in what size, guided by an explicit risk budget — the opposite of accumulating positions one trade idea at a time with no view of the whole.",
    relatedTermKeys: ["risk-contribution", "capital-allocation"],
    relatedLessonKeys: ["institutional-portfolio-construction"],
  },
  {
    key: "risk-contribution",
    term: "Risk Contribution",
    category: "institutional",
    definition: "How much of a portfolio's TOTAL risk a single position actually accounts for — not its dollar size alone, but its share of aggregate delta/theta/vega exposure and concentration. A small position in a volatile, correlated symbol can contribute disproportionate risk.",
    relatedTermKeys: ["concentration", "portfolio-construction"],
    relatedLessonKeys: ["institutional-risk-contribution"],
  },
  {
    key: "capital-allocation",
    term: "Capital Allocation",
    category: "institutional",
    definition: "Deciding how much of total available capital to deploy at all, and how to divide it across opportunities — a decision made before, and independent of, any single trade's own attractiveness.",
    relatedTermKeys: ["position-sizing", "buying-power"],
    relatedLessonKeys: ["institutional-capital-allocation"],
  },
  {
    key: "position-management",
    term: "Position Management",
    category: "institutional",
    definition: "The ongoing discipline of monitoring, adjusting, rolling, or closing an open position as conditions change — treating a trade as a managed process from entry to exit, not a decision made once and forgotten.",
    relatedTermKeys: ["risk-contribution", "decision-quality"],
    relatedLessonKeys: ["institutional-position-management"],
  },
  {
    key: "decision-quality",
    term: "Decision Quality",
    category: "institutional",
    definition: "Judging a decision by the soundness of the process and the information available at the time it was made — not by the outcome alone. A well-reasoned trade can still lose; a poorly-reasoned trade can still win. Institutional discipline separates the two.",
    relatedTermKeys: ["process-over-prediction", "position-management"],
    relatedLessonKeys: ["institutional-decision-quality"],
  },
  {
    key: "process-over-prediction",
    term: "Process over Prediction",
    category: "institutional",
    definition: "The core institutional mindset: build a repeatable, disciplined process (position sizing rules, defined risk, diversification, systematic entries/exits) rather than trying to correctly predict any single outcome — since no one can predict outcomes reliably, but a good process compounds over many trials.",
    relatedTermKeys: ["decision-quality", "expectancy"],
    relatedLessonKeys: ["institutional-process-over-prediction"],
  },

  // ─── Cross-cutting terms referenced above but not yet defined ─────────
  {
    key: "underlying",
    term: "Underlying",
    category: "foundations",
    definition: "The stock (or other asset) an option contract is written on. An option's value is derived from — and moves with — its underlying's price.",
    relatedTermKeys: ["stock", "option"],
    relatedLessonKeys: ["foundations-stocks"],
  },
  {
    key: "max-profit",
    term: "Maximum Profit",
    category: "performance",
    definition: "The most a defined-risk position can possibly make, known and fixed at entry — for a credit spread, typically the net credit received.",
    relatedTermKeys: ["max-loss", "return-on-capital"],
    relatedLessonKeys: ["performance-return-on-capital", "volatility-pricing-probability"],
  },
  {
    key: "max-loss",
    term: "Maximum Loss",
    category: "performance",
    definition: "The most a defined-risk position can possibly lose, known and fixed at entry — for a credit spread, typically the width between strikes minus the credit received.",
    relatedTermKeys: ["max-profit", "buying-power"],
    relatedLessonKeys: ["performance-return-on-capital", "volatility-pricing-probability", "options-risk-management"],
  },
  {
    key: "probability-of-profit",
    term: "Probability of Profit (POP)",
    category: "performance",
    definition: "The estimated chance a position finishes profitable by expiration, derived from delta with a volatility-risk-premium haircut applied (since implied volatility tends to overstate realized volatility). A high POP alone doesn't guarantee positive expected value — see Expectancy. POP being a real number does not mean the outcome is guaranteed: an 80% POP still means roughly 1 in 5 similar trades lose.",
    relatedTermKeys: ["delta", "expectancy", "expected-value"],
    relatedLessonKeys: ["performance-win-rate", "volatility-pricing-probability"],
  },
  {
    key: "expected-value",
    term: "Expected Value (EV)",
    category: "performance",
    definition: "The probability-weighted average dollar outcome of a single trade: (POP × max profit) − ((1 − POP) × max loss). A trade can have a high win rate and still have negative expected value if the loss on the rare miss is large enough. This platform computes and uses EV as a hard gate — a structure with EV at or below zero is rejected before it ever reaches a scanner result.",
    relatedTermKeys: ["probability-of-profit", "expectancy", "max-profit", "max-loss"],
    relatedLessonKeys: ["performance-expectancy", "volatility-pricing-probability"],
  },

  // ─── Value Investing (Phase 12 — Institutional Investing Engine
  // Consolidation & Integration). Every definition here describes an
  // already-existing, already-tested Engine 1 concept
  // (grahamValuation.ts/dcfValuation.ts/buffettValuation.ts/
  // investmentQuality.ts/competitiveAdvantage.ts/tomNashEngine.ts/
  // investmentCommittee.ts) — no new methodology is invented here, only
  // its definition. relatedLessonKeys is intentionally empty for these:
  // Value Investing School's own lessons (lib/valueSchool.ts) live in a
  // separate id-space from lib/learningPaths.ts' topic keys. ─────────────
  {
    key: "margin-of-safety",
    term: "Margin of Safety",
    category: "value-investing",
    definition: "The discount between a company's estimated fair (intrinsic) value and its current market price, expressed as a percentage. A larger margin of safety cushions an investor against errors in the valuation estimate or unforeseen bad news — Benjamin Graham's central risk-management idea.",
    relatedTermKeys: ["intrinsic-value", "graham-number"],
    relatedLessonKeys: [],
  },
  {
    key: "intrinsic-value",
    term: "Intrinsic Value",
    category: "value-investing",
    definition: "An estimate of what a business is actually worth, based on its underlying financials (earnings, assets, cash flow), independent of its current, possibly emotional, market price. Engine 1 computes several independent intrinsic-value estimates (Graham, DCF, Buffett, and a blended model) rather than a single number.",
    relatedTermKeys: ["margin-of-safety", "discounted-cash-flow", "graham-number"],
    relatedLessonKeys: [],
  },
  {
    key: "economic-moat",
    term: "Economic Moat",
    category: "value-investing",
    definition: "A durable competitive advantage that protects a company's profits from competitors over time — brand strength, network effects, switching costs, economies of scale, or regulatory protection. Rated Wide, Medium, Narrow, or None.",
    relatedTermKeys: ["competitive-advantage-dimensions", "capital-allocation-value"],
    relatedLessonKeys: [],
  },
  {
    key: "competitive-advantage-dimensions",
    term: "Competitive Advantage (11 Dimensions)",
    category: "value-investing",
    definition: "A broader, 11-dimension scoring framework beyond the classic economic moat — brand strength, network effects, switching costs, economies of scale, intangible assets, regulatory advantages, distribution, recurring revenue, cost advantages, competitive durability, and customer concentration risk.",
    relatedTermKeys: ["economic-moat"],
    relatedLessonKeys: [],
  },
  {
    key: "return-on-invested-capital",
    term: "Return on Invested Capital (ROIC)",
    category: "value-investing",
    definition: "How much operating profit a company generates for every dollar of capital (debt + equity) invested in the business. A consistently high ROIC, well above the company's cost of capital, is a hallmark of a durable competitive advantage.",
    relatedTermKeys: ["return-on-equity", "capital-allocation-value"],
    relatedLessonKeys: [],
  },
  {
    key: "return-on-equity",
    term: "Return on Equity (ROE)",
    category: "value-investing",
    definition: "Net income divided by shareholders' equity — how efficiently a company turns shareholders' own capital into profit. Unlike ROIC, ROE can be inflated by leverage (debt), so it is best read alongside debt levels and ROIC.",
    relatedTermKeys: ["return-on-invested-capital"],
    relatedLessonKeys: [],
  },
  {
    key: "owner-earnings",
    term: "Owner Earnings",
    category: "value-investing",
    definition: "Warren Buffett's preferred measure of a business's true cash-generating power, approximated here as free cash flow per share — the cash left over after the business reinvests what it needs to maintain its competitive position, available to be paid out to owners.",
    relatedTermKeys: ["free-cash-flow", "discounted-cash-flow"],
    relatedLessonKeys: [],
  },
  {
    key: "graham-number",
    term: "Graham Number",
    category: "value-investing",
    definition: "Benjamin Graham's conservative fair-value formula: the square root of (22.5 × trailing EPS × book value per share). Deliberately uses only trailing (already-reported) earnings, never a forward estimate, to avoid overpaying based on optimistic projections.",
    relatedTermKeys: ["margin-of-safety", "intrinsic-value"],
    relatedLessonKeys: [],
  },
  {
    key: "discounted-cash-flow",
    term: "Discounted Cash Flow (DCF)",
    category: "value-investing",
    definition: "A valuation method that projects a company's future free cash flows and discounts them back to a present value using a required rate of return, plus a terminal value for cash flows beyond the projection window. A historical, deterministic calculation applied to already-reported financials — not a prediction of a future stock price.",
    relatedTermKeys: ["free-cash-flow", "owner-earnings", "intrinsic-value"],
    relatedLessonKeys: [],
  },
  {
    key: "free-cash-flow",
    term: "Free Cash Flow (FCF)",
    category: "value-investing",
    definition: "Cash generated by operations minus capital expenditures — the cash a business actually has left over after keeping its operations running and its productive assets maintained, before any decision about dividends, buybacks, or debt paydown.",
    relatedTermKeys: ["owner-earnings", "discounted-cash-flow"],
    relatedLessonKeys: [],
  },
  {
    key: "financial-statements",
    term: "Financial Statements",
    category: "value-investing",
    definition: "The Income Statement, Balance Sheet, and Cash Flow Statement — this platform's Statements tab shows a genuine 5-year history of each, honestly labeled SIMULATED or LIVE, letting you check the actual dollar figures behind any computed ratio rather than trusting the ratio alone.",
    relatedTermKeys: ["free-cash-flow", "price-earnings-ratio"],
    relatedLessonKeys: [],
  },
  {
    key: "sec-filing-analysis",
    term: "SEC Filing Analysis",
    category: "value-investing",
    definition: "A company's most recent 10-K, fetched genuinely from SEC EDGAR — real government-filed data, independent of whether the platform's own fundamentals toggle is SIMULATED or LIVE. The platform's Management Quality scoring, built on top of this extracted text, is deterministic and never characterizes a named real individual.",
    relatedTermKeys: ["financial-statements"],
    relatedLessonKeys: [],
  },
  {
    key: "earnings-surprise",
    term: "Earnings Surprise",
    category: "value-investing",
    definition: "(Actual − Estimate) / |Estimate| for an already-reported quarter — always a backward-looking comparison against a real, already-happened result, never a forecast of an upcoming quarter.",
    relatedTermKeys: ["earnings-volatility"],
    relatedLessonKeys: [],
  },
  {
    key: "portfolio-beta",
    term: "Portfolio Beta",
    category: "portfolio",
    definition: "A market-cap-weighted average of each holding's own beta estimate, shown on Portfolio Construction's Risk tab as a plain informational badge — unlike the concentration and sector caps, breaching no particular beta level force-caps the overall risk score.",
    relatedTermKeys: ["concentration"],
    relatedLessonKeys: [],
  },
  {
    key: "concentration-cap",
    term: "Concentration Cap",
    category: "portfolio",
    definition: "A hard-coded threshold — 25% for a single symbol, 40% for a single sector — used identically across Portfolio Construction, the Decision Engine, the AI Coach, and Portfolio Optimisation. Breaching either cap force-caps the portfolio's overall risk score at 60, regardless of what the rest of the blend would otherwise produce.",
    relatedTermKeys: ["concentration", "portfolio-construction"],
    relatedLessonKeys: [],
  },
  {
    key: "book-value",
    term: "Book Value",
    category: "value-investing",
    definition: "A company's total assets minus its total liabilities, as reported on its balance sheet — a conservative, accounting-based measure of net worth used directly in the Graham Number formula.",
    relatedTermKeys: ["graham-number"],
    relatedLessonKeys: [],
  },
  {
    key: "price-earnings-ratio",
    term: "Price/Earnings (P/E) Ratio",
    category: "value-investing",
    definition: "Share price divided by earnings per share — the most common valuation shorthand, showing how many years of current earnings an investor is paying for. Best interpreted relative to a company's own trailing history and its industry peers, not in isolation.",
    relatedTermKeys: ["ev-ebitda"],
    relatedLessonKeys: [],
  },
  {
    key: "ev-ebitda",
    term: "EV/EBITDA",
    category: "value-investing",
    definition: "Enterprise Value divided by earnings before interest, taxes, depreciation, and amortization — a capital-structure-neutral valuation multiple that, unlike the P/E ratio, is unaffected by differences in debt levels or tax rates between companies.",
    relatedTermKeys: ["price-earnings-ratio"],
    relatedLessonKeys: [],
  },
  {
    key: "circle-of-competence",
    term: "Circle of Competence",
    category: "value-investing",
    definition: "Charlie Munger and Warren Buffett's discipline of only investing in businesses whose economics you can genuinely understand — how the business makes money, why it will likely keep making money, and what could destroy it. The boundary of the circle matters more than its size.",
    relatedTermKeys: ["business-quality-score"],
    relatedLessonKeys: [],
  },
  {
    key: "business-quality-score",
    term: "Business Quality Score",
    category: "value-investing",
    definition: "A 12-metric, 0-100 composite covering growth, margins, returns on capital, debt, cash position, and share dilution/buybacks — a structural read of how good the underlying business is, independent of whether its stock is currently cheap or expensive.",
    relatedTermKeys: ["capital-allocation-value", "return-on-invested-capital"],
    relatedLessonKeys: [],
  },
  {
    key: "capital-allocation-value",
    term: "Capital Allocation",
    category: "value-investing",
    definition: "How well a company's management deploys the cash it generates — reinvesting in the business, paying down debt, buying back shares, or paying dividends. Good capital allocation compounds shareholder value over time; poor allocation (e.g. diluting shareholders or overpaying for acquisitions) destroys it.",
    relatedTermKeys: ["business-quality-score", "return-on-invested-capital"],
    relatedLessonKeys: [],
  },
  {
    key: "conviction-score",
    term: "Conviction Score",
    category: "value-investing",
    definition: "A single 0-100 score blending Business Quality, Growth, Capital Allocation, Financial Strength, and Valuation into one composite read (the Tom Nash Conviction Engine), paired with a Buy/Hold/Wait classification — a summary of already-computed analysis, never a new prediction.",
    relatedTermKeys: ["business-quality-score", "margin-of-safety"],
    relatedLessonKeys: [],
  },
  {
    key: "portfolio-diversification-score",
    term: "Portfolio Diversification Score",
    category: "portfolio",
    definition: "A 0-100 composite measuring how spread out a portfolio's holdings are, based on position concentration (the Herfindahl-Hirschman Index) and the number of distinct sectors represented — a portfolio-level measure, distinct from any single company's own Business Quality Score.",
    relatedTermKeys: ["business-quality-score"],
    relatedLessonKeys: [],
  },
  {
    key: "portfolio-cash-allocation",
    term: "Cash Allocation (Portfolio)",
    category: "portfolio",
    definition: "The share of a target-allocation portfolio's own stated target weights left unassigned to any holding (100% minus the sum of target weights) — an honest measure of how fully a portfolio's own plan is invested, never a claim about an actual brokerage cash balance, which this platform does not observe.",
    relatedTermKeys: [],
    relatedLessonKeys: [],
  },
  {
    key: "growth-value-mix",
    term: "Growth vs. Value Mix",
    category: "portfolio",
    definition: "A portfolio-level breakdown classifying each holding as Growth, Value, or Blend, reusing that holding's own already-computed Tom Nash Growth pillar score and blended valuation rating — never a new judgment, just a portfolio-wide view of two signals already computed per company.",
    relatedTermKeys: ["conviction-score", "margin-of-safety"],
    relatedLessonKeys: [],
  },
  {
    key: "rebalancing-assistant",
    term: "Rebalancing Assistant",
    category: "portfolio",
    definition: "A suggested share count to buy or sell so a holding's actual weight moves back toward its own stated target weight — derived directly from a portfolio's own already-computed drift and current price, never a trade recommendation and never submitted, scheduled, or previewed as an order.",
    relatedTermKeys: [],
    relatedLessonKeys: [],
  },
  {
    key: "institutional-decision-engine",
    term: "Institutional Decision Engine",
    category: "value-investing",
    definition: "A deterministic synthesis layer that combines already-computed Business Quality, Competitive Advantage, Management Quality, Capital Allocation, Financial Strength, Valuation, Margin of Safety, the Investment Committee's verdict, and Tom Nash's conviction score into one Buy/Accumulate/Hold/Reduce/Sell/Avoid recommendation — never a new valuation model, never a price prediction.",
    relatedTermKeys: ["conviction-score", "margin-of-safety"],
    relatedLessonKeys: [],
  },
  {
    key: "investment-checklist",
    term: "Investment Checklist",
    category: "value-investing",
    definition: "A 15-item Pass/Warning/Fail (or honestly Unavailable) breakdown of a decision — Business Quality, Moat, Management, Capital Allocation, Revenue Growth, Margins, Cash Flow, Debt, ROIC, ROE, Valuation, Margin of Safety, Risk, Portfolio Fit, and Diversification — each item's status derived directly from an already-computed score or rating, never a new judgment.",
    relatedTermKeys: ["institutional-decision-engine"],
    relatedLessonKeys: [],
  },
  {
    key: "supporting-contradicting-evidence",
    term: "Supporting / Contradicting Evidence",
    category: "value-investing",
    definition: "Two lists surfacing the bullish and bearish facts behind a decision — moat strength, quality scores, committee votes, margin of safety, and balance-sheet flags — each restating an already-computed figure honestly on whichever side it supports, so a user can see the actual tension in the analysis rather than a single, papered-over verdict.",
    relatedTermKeys: ["institutional-decision-engine"],
    relatedLessonKeys: [],
  },
  {
    key: "decision-confidence-score",
    term: "Decision Confidence",
    category: "value-investing",
    definition: "A 0-100 score reused directly from the Investment Committee's own confidence (the average of the actual votes it cast), reported alongside the Institutional Decision Engine's recommendation — never a separately-fabricated probability of the recommendation being correct.",
    relatedTermKeys: ["institutional-decision-engine", "conviction-score"],
    relatedLessonKeys: [],
  },
  {
    key: "opportunity-discovery-engine",
    term: "Institutional Opportunity Discovery",
    category: "value-investing",
    definition: "A deterministic scanner that ranks a symbol universe using already-computed Business Quality, Valuation, Margin of Safety, the Investment Committee's verdict, Tom Nash's conviction score, and the Institutional Decision Engine's own synthesis score — never a new scoring model, never a price prediction, and never a fabricated result for data that genuinely doesn't exist (e.g. a company's country).",
    relatedTermKeys: ["institutional-decision-engine", "screener"],
    relatedLessonKeys: [],
  },
  {
    key: "screener",
    term: "Screener",
    category: "value-investing",
    definition: "A set of filter criteria (sector, market cap, ROIC, revenue growth, margin of safety, and more) applied to already-computed opportunity data — every filter reads an existing field, and a filter with no backing data anywhere in the codebase (Country) is honestly reported unavailable rather than silently ignored or approximated.",
    relatedTermKeys: ["opportunity-discovery-engine"],
    relatedLessonKeys: [],
  },
  {
    key: "opportunity-ranking",
    term: "Opportunity Ranking",
    category: "value-investing",
    definition: "The order opportunities are sorted in — by the Institutional Decision Engine's own already-computed synthesis score, descending — with a deterministic explanation quoting the real numbers behind that score, never an invented ranking formula.",
    relatedTermKeys: ["opportunity-discovery-engine", "institutional-decision-engine"],
    relatedLessonKeys: [],
  },
  {
    key: "opportunity-buckets",
    term: "Opportunity Buckets",
    category: "value-investing",
    definition: "Ten named categories (Top Opportunities, Undervalued, High Quality, Wide Moat, Dividend, Growth, Deep Value, Turnaround Candidates, Watchlist Candidates, Portfolio Upgrade Candidates) — each a disclosed, deterministic threshold or set rule over already-computed fields, never a new score.",
    relatedTermKeys: ["opportunity-discovery-engine"],
    relatedLessonKeys: [],
  },
  // ─── Institutional Monitoring & Alerts Engine ──────────────────────
  {
    key: "monitoring-alert",
    term: "Monitoring Alert",
    category: "value-investing",
    definition: "A change detected by continuously diffing already-computed engine output (Decision Engine recommendation, valuation, Business Quality, Investment Committee verdict, Tom Nash verdict, financial strength, dividends, portfolio drift, concentration caps, and saved-screen matches) against the last time it was checked — never a new scoring model. Every alert states its reason, evidence, previous value, current value, severity, and a recommended action.",
    relatedTermKeys: ["institutional-decision-engine", "opportunity-discovery-engine"],
    relatedLessonKeys: [],
  },
  {
    key: "alert-severity",
    term: "Alert Severity",
    category: "value-investing",
    definition: "A three-level classification (info/warning/critical) attached to every Monitoring Alert — a deterministic rule per alert type (e.g. a downgrade to a Sell/Avoid recommendation or a dividend cut to zero is critical; a hard-cap risk breach is a warning), never a subjective judgment.",
    relatedTermKeys: ["monitoring-alert"],
    relatedLessonKeys: [],
  },
  {
    key: "portfolio-drift-alert",
    term: "Portfolio Drift Alert",
    category: "value-investing",
    definition: "A Monitoring Alert fired when a portfolio's own quality score or diversification score has moved by 10 or more points since the last check — reusing the Institutional Portfolio Manager's own quality-drift scorecard and applying the identical drift-labeling pattern to diversification, never a new formula.",
    relatedTermKeys: ["monitoring-alert"],
    relatedLessonKeys: [],
  },
  {
    key: "watchlist-and-opportunity-triggers",
    term: "Watchlist & Opportunity Triggers",
    category: "value-investing",
    definition: "Two Monitoring Alert sources: a watchlist price or margin-of-safety target being crossed (Watchlist Trigger), and a new symbol appearing in a saved opportunity screen's top-ranked results (Opportunity Match) — the latter is deliberately on-demand only, never part of the automatic 5-minute check, since a full opportunity scan is real, non-trivial work.",
    relatedTermKeys: ["monitoring-alert", "opportunity-discovery-engine"],
    relatedLessonKeys: [],
  },

  // ─── Trading (Engine 2 — Phase 29's Institutional Trading AI Coach and its
  // learning path). Every term here defines a concept the Trading Coach's
  // 8 deterministic coaches (lib/tradingCoach.ts) or the Trade Planning &
  // Risk Studio already reference — no new methodology is invented here,
  // only its definition. ────────────────────────────────────────────────
  {
    key: "market-structure",
    term: "Market Structure",
    category: "trading",
    definition: "A trend classification (uptrend, downtrend, or range) derived from detecting swing highs/lows in real candle data — higher highs + higher lows read uptrend, lower highs + lower lows read downtrend, anything else honestly reads range rather than a forced direction.",
    relatedTermKeys: ["support-resistance-zone", "multi-timeframe-confluence"],
    relatedLessonKeys: [],
  },
  {
    key: "support-resistance-zone",
    term: "Support/Resistance Zone",
    category: "trading",
    definition: "A price level where multiple separate swing highs or lows have clustered — its 'strength' is simply how many swing touches were detected there, not a guarantee that price will react there again.",
    relatedTermKeys: ["market-structure"],
    relatedLessonKeys: [],
  },
  {
    key: "multi-timeframe-confluence",
    term: "Multi-Timeframe Confluence",
    category: "trading",
    definition: "The % of reviewed timeframes (e.g. 15m, 1h, 1D) that share the same dominant trend classification. 100% means every timeframe agrees; a split reading honestly reports no single dominant trend rather than guessing one.",
    relatedTermKeys: ["market-structure"],
    relatedLessonKeys: [],
  },
  {
    key: "swing-high-low",
    term: "Swing High / Swing Low",
    category: "trading",
    definition: "A candle whose high (or low) is at least as extreme as the 2 candles immediately before and after it — the platform's real, disclosed detection window. A standard professional trading concept, computed here with a fixed, non-configurable 5-candle window rather than a fractal or volume-weighted method.",
    relatedTermKeys: ["market-structure", "support-resistance-zone"],
    relatedLessonKeys: [],
  },
  {
    key: "break-of-structure",
    term: "Break of Structure (BoS)",
    category: "trading",
    definition: "A standard professional trading concept: a swing point being decisively broken in a way that continues the prevailing trend. This platform deliberately does not use this term or detect it as a distinct event anywhere — its own Structure Shift Timeline test suite explicitly asserts no event label ever matches BOS/CHOCH/MSS. A trader can still reason about the concept using the timeline's own real, honestly-labeled events (a fresh higher_high while already reading uptrend, for example) — but that reading is the trader's own interpretation, never a platform-computed label.",
    relatedTermKeys: ["change-of-character", "market-structure"],
    relatedLessonKeys: [],
  },
  {
    key: "change-of-character",
    term: "Change of Character (CHoCH)",
    category: "trading",
    definition: "A standard professional trading concept: the first swing break that signals a prevailing trend may be reversing, distinct from a break that merely continues it. This platform deliberately does not use this term or detect it as a distinct event — its Structure Shift Timeline only ever reports the flat, generic label trend_change for any non-range-to-non-range transition, with no computed distinction between a continuation break and a reversal break.",
    relatedTermKeys: ["break-of-structure", "market-structure"],
    relatedLessonKeys: [],
  },
  {
    key: "liquidity-band",
    term: "Liquidity Band",
    category: "trading",
    definition: "A High/Moderate/Low classification of a symbol's average dollar volume against named thresholds — a description of recent trading activity, not a directional signal.",
    relatedTermKeys: ["volume-profile", "buy-sell-pressure"],
    relatedLessonKeys: [],
  },
  {
    key: "volume-profile",
    term: "Volume Profile",
    category: "trading",
    definition: "A breakdown of which price levels carried the most real trading volume in a sampled candle window — descriptive of where activity actually occurred, not predictive of where price will go next.",
    relatedTermKeys: ["liquidity-band"],
    relatedLessonKeys: [],
  },
  {
    key: "buy-sell-pressure",
    term: "Buy/Sell Pressure",
    category: "trading",
    definition: "A proxy for directional volume, derived from each candle's own already-recorded up/down close — a bullish candle's volume counts toward buying pressure, a bearish candle's toward selling, never a separately fabricated imbalance number.",
    relatedTermKeys: ["liquidity-band"],
    relatedLessonKeys: [],
  },
  {
    key: "point-of-control",
    term: "Point of Control (POC)",
    category: "trading",
    definition: "A standard professional volume-profile concept: the single price level that traded the most volume in a session or sample window. This platform does not compute or label a POC anywhere — its own Volume Profile is an unlabeled, volume-sorted list of price buckets, and the top entry, while mathematically the highest-volume bucket, is never specially marked as a Point of Control by any code, route, or UI element.",
    relatedTermKeys: ["volume-profile", "value-area"],
    relatedLessonKeys: [],
  },
  {
    key: "value-area",
    term: "Value Area (VAH / VAL)",
    category: "trading",
    definition: "A standard professional volume-profile concept: the price range (typically containing ~70% of a session's volume around its Point of Control) bounded by a Value Area High and Value Area Low. This platform does not compute a value area anywhere — no code derives a 70%-of-volume band, and no VAH/VAL field exists on any object the platform returns.",
    relatedTermKeys: ["point-of-control", "volume-profile"],
    relatedLessonKeys: [],
  },
  {
    key: "vwap",
    term: "VWAP (Volume Weighted Average Price)",
    category: "trading",
    definition: "A standard professional trading concept: the average price a symbol traded at over a period, weighted by volume at each price. This platform does not compute VWAP, or a session-scoped VWAP, anywhere — a repository-wide search finds zero matches for the term or the underlying formula in any form, simulated or real.",
    relatedTermKeys: ["volume-profile", "point-of-control"],
    relatedLessonKeys: [],
  },
  {
    key: "trading-session",
    term: "Trading Session",
    category: "trading",
    definition: "A fixed, named UTC time window (Sydney, Tokyo, London, New York) — reference data, not a live feed. 'Active' means the current time falls inside that window's own start/end UTC hours.",
    relatedTermKeys: ["session-overlap"],
    relatedLessonKeys: [],
  },
  {
    key: "session-overlap",
    term: "Session Overlap",
    category: "trading",
    definition: "Two or more named trading sessions being open at the same time (e.g. London + New York) — a calendar fact about which fixed windows coincide, not itself a trading signal.",
    relatedTermKeys: ["trading-session"],
    relatedLessonKeys: [],
  },
  {
    key: "trading-position-sizing",
    term: "Position Sizing (Trading)",
    category: "trading",
    definition: "The number of shares a stated account-risk percentage allows, given a specific stop distance — pure arithmetic (account risk dollars ÷ per-share stop distance), not a recommendation on how large to trade. Distinct from Engine 1's own portfolio 'position-sizing' entry, which covers target-weight holdings rather than stop/target-based positions.",
    relatedTermKeys: ["risk-reward-ratio", "trading-capital-allocation"],
    relatedLessonKeys: [],
  },
  {
    key: "risk-reward-ratio",
    term: "Risk/Reward Ratio",
    category: "trading",
    definition: "The planned reward distance (entry to target) divided by the planned risk distance (entry to stop) — a fact about the numbers entered into a Trade Plan or Scenario, never a judgment on whether those levels are well placed.",
    relatedTermKeys: ["trading-position-sizing", "trade-plan"],
    relatedLessonKeys: [],
  },
  {
    key: "trading-capital-allocation",
    term: "Capital Allocation (Trading)",
    category: "trading",
    definition: "The aggregate dollar risk across every stop-defined open position, scored against a named portfolio-wide cap — distinct from Engine 1's own portfolio capital-allocation concept, since Engine 2's positions are stop/target-based rather than target-weight-based.",
    relatedTermKeys: ["portfolio-risk-budget"],
    relatedLessonKeys: [],
  },
  {
    key: "portfolio-risk-budget",
    term: "Portfolio Risk Budget",
    category: "trading",
    definition: "The Risk Management Engine's own scored component covering total open-position dollar risk against a named cap, with an honest hard-cap override that floors the overall risk score if the cap is breached, regardless of how the other components scored.",
    relatedTermKeys: ["trading-capital-allocation", "trading-position-sizing"],
    relatedLessonKeys: [],
  },
  {
    key: "trade-plan",
    term: "Trade Plan",
    category: "trading",
    definition: "A human's own stated pre-trade intent — direction, entry, stop, target, account risk %, and thesis — saved before a position is opened, distinct from an already-open position and never machine-generated.",
    relatedTermKeys: ["risk-reward-ratio", "scenario-comparison"],
    relatedLessonKeys: [],
  },
  {
    key: "scenario-comparison",
    term: "Scenario Comparison",
    category: "trading",
    definition: "A stateless, non-persisted side-by-side comparison of 2-5 candidate entry/stop/target combinations, each run through the same Trade Plan arithmetic — 'Best R:R' and 'Tightest Risk' are honest max/min identifications, never a recommendation on which scenario to take.",
    relatedTermKeys: ["trade-plan", "risk-reward-ratio"],
    relatedLessonKeys: [],
  },
  {
    key: "trading-journal",
    term: "Trading Journal",
    category: "trading",
    definition: "A user's own recorded reflections on their trades — title, content, mood, tags, lesson learned, setup type, and (optionally) an R-multiple — read-only source data for the Journal Coach and Psychology & Discipline Coach, never a source of new judgments about the user.",
    relatedTermKeys: ["r-multiple"],
    relatedLessonKeys: [],
  },
  {
    key: "r-multiple",
    term: "R-Multiple",
    category: "trading",
    definition: "A trade's realized profit or loss expressed as a multiple of the amount originally risked (e.g. +2R means the trade gained twice the risked amount) — a number the user records themselves on a Journal entry, never recomputed or inferred by the platform.",
    relatedTermKeys: ["trading-journal"],
    relatedLessonKeys: [],
  },
  {
    key: "trading-strategy-framework",
    term: "Strategy Framework",
    category: "trading",
    definition: "A reusable structure (Phase 30) that lets a user register their own trading methodology as METADATA — name, description, category, timeframes, markets, required evidence, a checklist template, educational notes, references, and version — without the platform implementing, evaluating, or generating any signal for that methodology.",
    relatedTermKeys: ["strategy-checklist", "strategy-evidence-link"],
    relatedLessonKeys: [],
  },
  {
    key: "strategy-checklist",
    term: "Strategy Checklist",
    category: "trading",
    definition: "A specific, persisted instance of a strategy's own checklist template applied to one real use — tracking completion state, per-item notes, and evidence links. Every item's label and required/optional flag is copied from the parent strategy's own user-authored template; the platform never hardcodes checklist content.",
    relatedTermKeys: ["trading-strategy-framework", "strategy-evidence-link"],
    relatedLessonKeys: [],
  },
  {
    key: "strategy-evidence-link",
    term: "Strategy Evidence Link",
    category: "trading",
    definition: "A citation packaging a label, detail, and optional deep link back to an already-computed engine output (Market Structure, Liquidity, Sessions, Risk, Trade Plans, Journal, or the Trading AI Coach) — never a calculation of its own, only a reference trail proving where a piece of supporting evidence came from.",
    relatedTermKeys: ["trading-strategy-framework", "strategy-checklist"],
    relatedLessonKeys: [],
  },

  // ─── Platform Basics (v1.4.0, Sprint L1 — Learning Centre Foundation) ──
  {
    key: "session",
    term: "Session",
    category: "platform",
    definition: "Your authenticated, signed-in state with the platform. Every page you visit and every action you take is scoped to your own session — no data from another user's session is ever visible to you.",
    relatedTermKeys: ["tenant"],
    relatedLessonKeys: ["platform-basics-navigation"],
  },
  {
    key: "tenant",
    term: "Tenant",
    category: "platform",
    definition: "The account-level boundary every piece of your data (trades, journal entries, portfolios, settings) is scoped to. Every route in this platform is tenant-isolated — one user's data is never readable by another.",
    relatedTermKeys: ["session"],
    relatedLessonKeys: ["platform-basics-navigation"],
  },
  {
    key: "kill-switch",
    term: "Kill Switch",
    category: "platform",
    definition: "A master on/off toggle (in Settings) that instantly disables the automation engines (Full-Auto trade opening and Auto-Adjustment) for your account. Flipping it off is the fastest safety action available if you're ever unsure whether automation should keep running.",
    relatedTermKeys: ["guardrail"],
    relatedLessonKeys: ["platform-basics-navigation"],
  },
  {
    key: "guardrail",
    term: "Guardrail",
    category: "platform",
    definition: "A hard, deterministic limit (a daily trade cap, a concurrent-position cap, a score floor, a daily-loss circuit breaker) that the automation engines check before taking any action — never a suggestion, always enforced.",
    relatedTermKeys: ["kill-switch"],
    relatedLessonKeys: ["platform-basics-navigation"],
  },
  {
    key: "command-palette",
    term: "Command Palette",
    category: "platform",
    definition: "The global search dialog (⌘K / Ctrl+K) that finds any page, position, watchlist entry, portfolio, lesson, strategy, or glossary term across the whole platform — one search surface for everything, not a separate search per page.",
    relatedTermKeys: [],
    relatedLessonKeys: ["platform-basics-navigation"],
  },
  {
    key: "simulated-vs-live",
    term: "SIMULATED vs. LIVE",
    category: "platform",
    definition: "A data-source label every engine attaches to its own figures. SIMULATED means the number was deterministically generated for demonstration/testing, never a real market quote or brokerage fill. LIVE means it came from a real, connected data or broker provider. This platform runs SIMULATED by default; Live Trading remains disabled.",
    relatedTermKeys: [],
    relatedLessonKeys: ["platform-basics-navigation"],
  },

  // ─── AI Coach & Institutional Mentor Academy (v1.4.0, Sprint L2J) ──────
  {
    key: "llm-narration-source",
    term: "LLM Narration Source",
    category: "platform",
    definition: "The `source` field ('llm' or 'template') every genuinely AI-narrated feature on this platform attaches to its own output. 'llm' means the text was generated by a real language model call (Anthropic or OpenAI, whichever API key is configured); 'template' means no key was configured (or the call failed/timed out) and the platform fell back to deterministic, pre-written text instead — never silently pretending a template response came from a model.",
    relatedTermKeys: ["deterministic-ai-coach", "coach-disclaimer"],
    relatedLessonKeys: ["ai-team-overview", "ai-understanding-responses"],
  },
  {
    key: "deterministic-ai-coach",
    term: "Deterministic AI Coach",
    category: "platform",
    definition: "A platform feature named 'AI Coach,' 'Mentor,' or similar that is, in fact, entirely rule-based — built from fixed logic, thresholds, and pre-written explanation templates, with zero calls to any language model. Several coach-named modules on this platform (including the Institutional Trading AI Coach and the AI Portfolio Analyst) work this way by design: consistent, explainable, and free of the variability a real LLM would introduce. Distinguishing these from genuinely LLM-generated narration is one of this platform's core AI-literacy skills.",
    relatedTermKeys: ["llm-narration-source", "coach-disclaimer"],
    relatedLessonKeys: ["ai-team-overview", "ai-understanding-responses"],
  },
  {
    key: "coach-disclaimer",
    term: "Coach Disclaimer",
    category: "platform",
    definition: "The mandatory disclaimer text every AI narration path on this platform enforces before returning its response to you — stating plainly that the output is informational/educational, not financial advice, and that automated systems can be wrong. Every genuinely LLM-backed coach on this platform routes through this same shared enforcement so the disclaimer can never be silently dropped, whichever engine or persona is generating the text.",
    relatedTermKeys: ["llm-narration-source"],
    relatedLessonKeys: ["ai-team-overview", "ai-understanding-responses"],
  },

  // ─── Professional Institutional Workflows Academy (v1.4.0, Sprint L2K) ─
  {
    key: "ravish-score",
    term: "Ravish Score",
    category: "trading",
    definition: "The real, computed opportunity score every Scanner result carries — genuinely used as a hard execution gate, not just a display number: AutoPilot's automated cycle rejects any candidate whose Ravish Score falls below the platform's configured floor before it's ever eligible for auto-execution.",
    relatedTermKeys: [],
    relatedLessonKeys: ["workflow-professional-trade"],
  },
  {
    key: "review-workflow-cadence",
    term: "Review Workflow Cadence",
    category: "platform",
    definition: "A descriptive label (daily/weekly/monthly/quarterly/ad hoc) attached to a named review workflow in the Portfolio Workspace's Workflow Center — a tag describing how often a professional would typically run that workflow, never a scheduler. Starting an instance, checking off its steps, and completing it are always a manual, user-initiated action; nothing on this platform fires a workflow automatically on a calendar.",
    relatedTermKeys: [],
    relatedLessonKeys: ["workflow-weekly-monthly-review"],
  },
];

export function searchGlossary(query?: string, category?: GlossaryCategory): GlossaryTerm[] {
  let results = GLOSSARY_TERMS;
  if (category) {
    results = results.filter((t) => t.category === category);
  }
  if (query && query.trim().length > 0) {
    const q = query.trim().toLowerCase();
    results = results.filter(
      (t) => t.term.toLowerCase().includes(q) || t.definition.toLowerCase().includes(q) || t.key.includes(q),
    );
  }
  return [...results].sort((a, b) => a.term.localeCompare(b.term));
}

export function getGlossaryTerm(key: string): GlossaryTerm | null {
  return GLOSSARY_TERMS.find((t) => t.key === key) ?? null;
}

export function glossaryCategories(): GlossaryCategory[] {
  return ["foundations", "greeks", "volatility", "strategies", "portfolio", "performance", "institutional", "value-investing", "trading", "platform"];
}
