import { Router, type IRouter } from "express";
import scannerRouter from "./scanner";
import optionsRouter from "./options";
import portfolioRouter from "./portfolio";
import portfolioAIRouter from "./portfolioAI";
import tradesRouter from "./trades";
import executionRouter from "./execution";
import autoExecutionRouter from "./autoExecution";
import backtestRouter from "./backtest";
import scoringRouter from "./scoring";
import journalRouter from "./journal";
import aiRouter from "./ai";
import coachRouter from "./coach";
import settingsRouter from "./settings";
import performanceRouter from "./performance";
import marketDataHealthRouter from "./marketDataHealth";
import brokerHealthRouter from "./brokerHealth";
import brokerReconciliationRouter from "./brokerReconciliation";
import eventsRouter from "./events";
import stockAnalystRouter from "./stockAnalyst";
import portfolioConstructionRouter from "./portfolioConstruction";
import tradingJournalRouter from "./tradingJournal";
import tradingStructureRouter from "./tradingStructure";
import tradingMultiTimeframeRouter from "./tradingMultiTimeframe";
import tradingRegimeRouter from "./tradingRegime";
import tradingProbabilityRouter from "./tradingProbability";
import tradingPositionsRouter from "./tradingPositions";
import tradingRiskRouter from "./tradingRisk";
import tradingLiquidityRouter from "./tradingLiquidity";
import tradingCoachRouter from "./tradingCoach";
import tradingBacktestRouter from "./tradingBacktest";
import notificationsRouter from "./notifications";
import optionsBacktestRouter from "./optionsBacktest";
import crossEngineDailyReportRouter from "./crossEngineDailyReport";
import orderPreviewRouter from "./orderPreview";
import positionSizingRouter from "./positionSizing";
import tradeAdjustmentPreviewRouter from "./tradeAdjustmentPreview";
import portfolioStressTestRouter from "./portfolioStressTest";
import portfolioEventRiskRouter from "./portfolioEventRisk";
import portfolioConcentrationRouter from "./portfolioConcentration";

const router: IRouter = Router();

router.use(scannerRouter);
router.use(optionsRouter);
router.use(portfolioRouter);
router.use(portfolioAIRouter);
router.use(tradesRouter);
router.use(executionRouter);
router.use(autoExecutionRouter);
router.use(backtestRouter);
router.use(scoringRouter);
router.use(journalRouter);
router.use(aiRouter);
router.use(coachRouter);
router.use(settingsRouter);
router.use(performanceRouter);
router.use(marketDataHealthRouter);
router.use(brokerHealthRouter);
router.use(brokerReconciliationRouter);
router.use(eventsRouter);
router.use("/stock-analyst", stockAnalystRouter);
router.use(portfolioConstructionRouter);
router.use(tradingJournalRouter);
router.use(tradingStructureRouter);
router.use(tradingMultiTimeframeRouter);
router.use(tradingRegimeRouter);
router.use(tradingProbabilityRouter);
router.use(tradingPositionsRouter);
router.use(tradingRiskRouter);
router.use(tradingLiquidityRouter);
router.use(tradingCoachRouter);
router.use(tradingBacktestRouter);
router.use(notificationsRouter);
router.use(optionsBacktestRouter);
router.use(crossEngineDailyReportRouter);
router.use(orderPreviewRouter);
router.use(positionSizingRouter);
router.use(tradeAdjustmentPreviewRouter);
router.use(portfolioStressTestRouter);
router.use(portfolioEventRiskRouter);
router.use(portfolioConcentrationRouter);

export default router;
